### ISSUE TITLE
请问解析原始牌谱的数据是哪个文件？

### ISSUE THREAD

**Issue by Agony5757** [zyr17/MajsoulPaipuAnalyzer#1]
另外还想问一下在解析后的牌谱种，每个役种的编号都是什么？

**Comment by zyr17** [comment]
SimpleMahjong/paipu.js的majsoulpaipuanalyze类。输入牌谱的函数是getfile...等定义在最后的四个函数。解析后转换是SimpleMahjong/index.js的Viewprototype，这是牌桌显示接口，接口收到指令在显示同时会写this.roundrecord和this.gamerecord来完成自己牌谱的记录。

牌谱编号在SimpleMahjong/const.js，hanname是自己牌谱格式对应的名称，这个是当年从网上找的天凤牌谱编号。majsoulfanid2name是雀魂的编号对应。

**Comment by zyr17** [comment]
另外代码是我以前不知道protobuf的情况下写的，暴力解析十分丑陋。之后有时间应该会重写。
