### ISSUE TITLE
检查四家立直

### ISSUE THREAD

**Issue by zyr17** [zyr17/MajsoulPaipuAnalyzer#13]
雀魂触发四家立直不需要给棒子?

**Comment by NachtgeistW** [comment]
四家立直是这样，四支立直棒会留在桌上，下一局谁和牌了就谁拿走这四支立直棒（即4000点）。

**Comment by zyr17** [comment]
感谢说明。之前是看到录像出发四家立直时第四家没有放点棒的动画，现在通过回放确认下一局开始会有4根供托，只是少了动画，四家都给了1000点。
