### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by NachtgeistW** [zyr17/MajsoulPaipuAnalyzer#16]
- 放铳役种里面的自摸可以“删掉”；
- 是“三色同顺”不是“三色通顺”；

**Comment by NachtgeistW** [comment]
还有就是能不能把古役也加上

**Comment by zyr17** [comment]
感谢您的建议，我之后会修复bug。关于古役，之前只分析四人排位场和友人场牌谱，同时当时友人场不存在古役，因此没有纳入分析。现在友人古役场应该会出bug导致牌谱无法转换。个人考虑从数据分析角度古役对于提高水平用处不大，之后我会考虑是排除古役牌谱还是增加古役分析。
