### ISSUE TITLE
登陆时使用谷歌账号登陆会显示浏览器不安全

### ISSUE THREAD

**Issue by btsrkex** [zyr17/MajsoulPaipuAnalyzer#17]
然后登陆不了
不是邮箱登陆发验证码,是直接谷歌账号

**Comment by btsrkex** [comment]
![QQ截图20200216105002](https://user-images.githubusercontent.com/34084904/74598299-2bef8000-50aa-11ea-8228-4bc89356ae8d.jpg)

**Comment by zyr17** [comment]
已经修复，可以试一下新版本是否能够使用。
