### ISSUE TITLE
关于增加一个期望得点的建议

### ISSUE THREAD

**Issue by NaughtyTiger** [zyr17/MajsoulPaipuAnalyzer#2]
有一个以前玩天凤的牌手，提到在天凤上有一个“安定段”的概念，就是说能够让你知道你按目前的胜率，最终会到达什么段位。
其算法为：先得到四个名次的比例，以及四个名次的**平均得点**，就能得到当前段位的每局的期望得点。比如说我是雀圣一段，期望得点是+10；
然后假设我已经是雀圣二段了，那么我的第四名就要多扣分，结合第四名的概率，就会得到一个新的期望得点，比如说是-10；
那么我的安定段就是雀圣1.5段。

总的来说，获得**平均得点**就能做一些事情。

**Comment by zyr17** [comment]
感谢说明，有不少人和我提过安定段位的计算了，我目前转换存储的数据只有每场结束后每个人的得点变化，没有每个人的段位和初始PT，只是上述的数据的话应该还是可以算的。只不过这么看来计算安定段位需要基于同级别的对战吧？我会思考一下怎么实现和展示数据。

对战时对手的段位应该也有参考价值，虽然我目前缺少这块数据，也不知道怎么算。。

**Comment by NaughtyTiger** [comment]
在0.2.8中算出来我的安定段是10+，我还看到有18+的，我有点疑惑

**Comment by zyr17** [comment]
这个我觉得是正常的。首先，通过目前场次计算的安定段位在场次少时本身就存在巨大的波动。天凤的算分和雀魂相近，以天凤的段位分计算规则为例，在有1000场次的时候，仍有5%的概率真实实力偏离计算所得安定段位1.4段以上，在10000场次下仍有95%概率偏离0.5段以上；同时随着场次增加水平也是会上升的，因此安定段位实际上只能做很粗略的参考，不要过于纠结。

然后是关于计算出来的安定段位的值的问题。以我自己为例，我在金南有160场战斗，安定段位5.33。这和我自己当时打金南的感受是比较接近的，我刚上杰1时打不动还掉过段，大概花了快80场才上杰2，杰2到3也有过掉星经历。之后水平有所上升+金场变菜了升豪没有碰到太强的阻力比较顺利，和5.3段（超过3段所以能上豪；但是并不高太多所以最开始打的不行）基本相符；同样目前雀豪是0.4段，我目前就是豪1负分选手但是也没有输的太惨所以是缓慢掉分。再举个银东，我是17段，因为我银以上就只打南，当初杰2快掉星的时候没钱了去银东混了几十把打出了40%一位35%二位。所以如果出现安定段位很高的话说明正在快速上分，马上就可以去下一级房间杀鸡了_(:3」∠)_。如果是玉场数据安定十几的话。。大佬请受我一拜，顺便求一下gamedata和paipus的文件，这真的有可能是我写错了。。

**Comment by NaughtyTiger** [comment]
是金场：）

**Comment by zyr17** [comment]
如果现在的金场和我打的时候差不多的话，那说明你上去肯定不是我这种菜鸡负分豪一了~
