### ISSUE TITLE
MacOS，MajsoulPaipuCrawler打开即报错，文件读写权限问题

### ISSUE THREAD

**Issue by daqian-polestar** [zyr17/MajsoulPaipuAnalyzer#29]
Dear,

运行报错如下：
<img width="596" alt="image" src="https://user-images.githubusercontent.com/81152515/113398180-c1de8b00-93d0-11eb-99d6-02b4cde32d07.png">

系统版本：
<img width="586" alt="image" src="https://user-images.githubusercontent.com/81152515/113398243-d884e200-93d0-11eb-9eb6-7a3360a4e504.png">

有人知道解决方案么，万分感谢🙏

**Comment by jjjjjeffrey** [comment]
我也是这个问题，求解

**Comment by zyr17** [comment]
我自己没有mac，不太好确定是什么问题。只看报错的话是说没有写入权限，可能是mac的什么设置让文件变成只读了，导致没有办法往配置文件里写数据。

在引入了修罗模式以后牌谱变化比较大，大多不能正常分析了，不是mac也有问题。。最近挤不出什么空闲时间，修bug可能需要等上一段时间了

**Comment by jjjjjeffrey** [comment]
没关系，有空再说吧

**Comment by jjjjjeffrey** [comment]
刚才闲来无事重新编译了一下，运行不报错了 @zyr17

**Comment by alexfan07** [comment]
同样问题

**Comment by zyr17** [comment]
@alexfan07 我手头没有MacOS设备，Mac编译是比较久以前配置的action，暂时无法确认是什么问题。您可以试试把报错信息问问google和chatgpt _(:3」∠)_
