### ISSUE TITLE
MacOS PaipuAnalyzer报错Segmentation Fault

### ISSUE THREAD

**Issue by nzpznk** [zyr17/MajsoulPaipuAnalyzer#31]
下载牌谱可以正常完成，但是使用PaipuAnalyzer进行分析的时候会自动退出，使用 #9 中提到的debug版程序同样segmentation fault，debug.log文件为空。echo $? 得到退出码139

**Comment by zyr17** [comment]
感谢您的回复。

出现修罗模式后在牌谱分析部分出现问题，由于近期实在没有空闲时间，短期内没有办法抽空修复了，目前工具处于罢工状态。之后有时间了会尽快修复问题。

**Comment by zyr17** [comment]
已更新新版本，跳过了特殊规则的牌谱分析和转换，可以试用下看看还有没有问题。
