### ISSUE TITLE
paipuanalyzer打开之后闪退

### ISSUE THREAD

**Issue by xtzhjj** [zyr17/MajsoulPaipuAnalyzer#33]
录屏发现闪过了活动代码页936

**Comment by zyr17** [comment]
是不是您的友人场有修罗模式的数据？新模式会导致牌谱转换不能正常工作，生成有问题的数据，引起分析器崩溃。我这两天正在着手修复该问题，等修复好后您可以尝试使用新的0.4.6版看问题解决了没有。

**Comment by zyr17** [comment]
已更新新版本，跳过了特殊规则的牌谱分析和转换，可以试用下看看还有没有问题。

**Comment by xtzhjj** [comment]
OK了可以用了
