### ISSUE TITLE
获取的牌谱数据 盘数和局数对不上 排名比例也跟实际不符

### ISSUE THREAD

**Issue by LMarTinnnn** [zyr17/MajsoulPaipuAnalyzer#35]
![1](https://user-images.githubusercontent.com/20036303/129194632-959e630a-0e88-40c9-ba0b-8fb515f9b2c3.PNG)
盘数和局数相比有明显异常
一二三四位的占比也跟游戏内有较大出入

烦请大佬空闲时间看看是什么情况~ Thanks♪(･ω･)ﾉ

**Comment by LMarTinnnn** [comment]
前面那个121场在牌谱屋看到是1244局 1位率25.62%

**Comment by zyr17** [comment]
感谢您的反馈，最近因为雀魂变更了牌谱接口所以前段时间修了无法获取牌谱的BUG，但是因为修完以后也没时间打就没注意到新牌谱分析的问题。我这边去友人局打了几把已经发现数据丢失的情况了，这两天有空时会着手修复，但是排位问题我这边没有复现。如果方便的话，能否将最近这55盘的牌谱文件（存于data/majsoul/%ID%/raw/内，牌谱以日期开头比较好找）和牌谱屋上关于近期几盘的数据截图提供一下？这样我能更好确定排位出了什么问题，以及有没有成功修复，谢谢。

2021年8月12日(木) 20:43 ptwylxs ***@***.***>:

**Comment by zyr17** [comment]
新版0.4.9牌谱分析已经修复了。数据问题我这边目前没有观测到问题牌谱，等到发现问题了就会修复。

**Comment by LMarTinnnn** [comment]
使用新版后已经没有问题了！ Thanks♪(･ω･)ﾉ
