### ISSUE TITLE
可否提供下载任意牌谱的功能？

### ISSUE THREAD

**Issue by ainokiseki** [zyr17/MajsoulPaipuAnalyzer#36]
我在尝试编写一个分析选手牌效率的程序，但js基础为0，在获取牌谱时遇到了问题。注意到您的程序可以下载并转换用户本人的牌谱，那么理论上也可以下载用户所能查看到的所有牌谱。能否增加一个下载用户提供地址的牌谱的功能？谢谢！

**Comment by zyr17** [comment]
因为工具整体逻辑是针对个人的牌谱分析，所以目前没有支持。我用于debug写了一个下载raw牌谱文件的接口，但是并没有对牌谱进行转换。

请问您想要的是哪种类型？是直接raw牌谱就行还是需要转换好后我定义的json格式的牌谱？如果是前者的话，您可以如下操作：在工具中登陆游戏；菜单中选择其他-关于，点击确定；菜单中选择其他-关于，点击取消；菜单中选择其他-下载牌谱并保存，输入牌谱地址/牌谱号；选择牌谱保存位置。如果是后者的话，目前还暂时无法实现。

另：之前也了解到了有类似需求的用户，准备实现下载任意牌谱数据，以及对牌谱数据内指定用户分析的功能，应该和你需要的功能有重合？虽然目前还不能保证什么时候搞完，您可以等待一段时间，我应该会在近期加入上述功能。

**Comment by ainokiseki** [comment]
已成功下载，我研究一下怎么解析raw牌谱，感谢您的回复！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyr17/MajsoulPaipuAnalyzer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyr17/MajsoulPaipuAnalyzer] 可否提供下载任意牌谱的功能？ (#36)





 
因为工具整体逻辑是针对个人的牌谱分析，所以目前没有支持。我用于debug写了一个下载raw牌谱文件的接口，但是并没有对牌谱进行转换。
 
请问您想要的是哪种类型？是直接raw牌谱就行还是需要转换好后我定义的json格式的牌谱？如果是前者的话，您可以如下操作：在工具中登陆游戏；菜单中选择其他-关于，点击确定；菜单中选择其他-关于，点击取消；菜单中选择其他-下载牌谱并保存，输入牌谱地址/牌谱号；选择牌谱保存位置。如果是后者的话，目前还暂时无法实现。
 
另：之前也了解到了有类似需求的用户，准备实现下载任意牌谱数据，以及对牌谱数据内指定用户分析的功能，应该和你需要的功能有重合？虽然目前还不能保证什么时候搞完，您可以等待一段时间，我应该会在近期加入上述功能。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyr17** [comment]
雀魂牌谱使用protobuf作为数据通信格式，我的相关解析代码在lib/majsoul/analyze.js中，供您参考。

**Comment by zyr17** [comment]
近期实现了一个包含公共牌谱池的版本，可以将一系列牌谱下载至公共牌谱池并分析某个指定玩家的数据。测试版链接如下：
https://github.com/zyr17/MajsoulPaipuAnalyzer/actions/runs/1250979369
目前仅包含windows版，其他平台请clone代码并在对应平台编译。
