### ISSUE TITLE
点击进入中文服和进入日服没反应，只有国际服能正常进入

### ISSUE THREAD

**Issue by waveyl** [zyr17/MajsoulPaipuAnalyzer#43]
![image](https://user-images.githubusercontent.com/22638873/164952436-14cb6a90-8940-4995-8dc4-587689294ea7.png)
![image](https://user-images.githubusercontent.com/22638873/164952446-fdf30edb-9a1d-4c10-8bbf-43b1d7614096.png)
使用登录专用窗口也一样

**Comment by zyr17** [comment]
我这边测试行为正常。请检查您的网络是否通畅，不使用该工具的情况下，使用系统浏览器能否连接日服和国服。

工具默认应该是会走系统代理的，如果浏览器访问使用了代理工具，请确认开启了全局代理，让该工具也能通过代理访问。

**Comment by waveyl** [comment]
确实是代理的问题，感谢
