### ISSUE TITLE
检查雀魂随机性的建议

### ISSUE THREAD

**Issue by Neerdge** [zyr17/MajsoulPaipuAnalyzer#6]
虽然雀魂为牌山公开了MD5，但并未公开其算法，而MD5和麻将排列又有很高的简并性，故不能证明其牌山为随机生成。
同时，有相当一部分人质疑雀魂运营不到一年，就出现了天凤数年闻所未闻的神仙牌谱，存在暗改配牌的可能。
可以从以下角度验证雀魂的随机性：

1. 起手向听数
2. 立直后一发自摸率
3. 中里宝数量/宝牌指示牌数量

1和3是验证随机性的重要证据。目前雀魂的一发率和里宝数量明显比天凤数据高，其原因可能是雀魂玩家水平较差/头更铁、雀魂玩家开杠更频繁。
在雀魂官方给出解释前，希望这些数据能消除部分玩家的顾虑。

**Comment by zyr17** [comment]
我这个工具的初衷是个人牌谱数据分析，当然修改一下做大量分析也是可行的（这也是我开始做这个工具的目的之一）。
但是最主要的问题是首先我得拿到大量牌谱才行，目前工具一次只能收集一个用户的牌谱数据，而且雀魂网页也有最多浏览1000个牌谱的限制。即使找到了方法绕过这个限制，单单一个人顶多几千个牌谱做这种验证还是不太行的（这是凭感觉的，到底1000级别的牌谱能不能做这种分析我有空的时候会算一下），需要雀魂像天凤的凤桌一样主动公开大量牌谱记录。

**Comment by Neerdge** [comment]
给雀魂官方发了邮件，我总觉得这次汪汪录起手三九神仙进张国士有问题。

**Comment by zyr17** [comment]
当时我觉得数据规模不够，后来仔细算了一下，由于一张南风牌谱会打约10场，每场有三家的起手手牌（雀魂庄家直接配14张牌且排好序了就没统计），数据量上来说还是比较大的，除了一些概率极低的极端情况都是能够统计的。下面统计了向听数；除国士七对的向听数；以及每张牌出现次数的分布，结果没怎么整理格式见谅：
------
概率统计
43758 start hand analyzed
shanten result (0-6):
0.000137118 0.00644454 0.0941085 0.362631 0.396659 0.131359 0.00866127
shanten without chitoi kokushi result (0-8):
0.000137118 0.00537045 0.07802 0.309315 0.382376 0.186709 0.0360163 0.00203391 2.2853e-05
tiles result:
[1m 0.379542] [2m 0.381119] [3m 0.383976] [4m 0.378559] [5m 0.290141] 
[0m 0.0961424] [6m 0.381942] [7m 0.378262] [8m 0.38105] [9m 0.387906]
[1p 0.383861] [2p 0.382193] [3p 0.385689] [4p 0.384227] [5p 0.285708] 
[0p 0.097148] [6p 0.380959] [7p 0.381165] [8p 0.385872] [9p 0.383724]
[1s 0.383496] [2s 0.380548] [3s 0.382467] [4s 0.381759] [5s 0.289296] 
[0s 0.0955482] [6s 0.38169] [7s 0.380479] [8s 0.38361] [9s 0.379656]
[1z 0.375131] [2z 0.381827] [3z 0.380296] [4z 0.383016] [5z 0.383998] 
[6z 0.382947] [7z 0.38505]
------
次数统计
43758 start hand analyzed
shanten result (0-6):
6 282 4118 15868 17357 5748 379
shanten without chitoi kokushi result:
6 235 3414 13535 16732 8170 1576 89 1
tiles result (0-8):
[1m 16608] [2m 16677] [3m 16802] [4m 16565] [5m 12696] 
[0m 4207] [6m 16713] [7m 16552] [8m 16674] [9m 16974]
[1p 16797] [2p 16724] [3p 16877] [4p 16813] [5p 12502] 
[0p 4251] [6p 16670] [7p 16679] [8p 16885] [9p 16791]
[1s 16781] [2s 16652] [3s 16736] [4s 16705] [5s 12659] 
[0s 4181] [6s 16702] [7s 16649] [8s 16786] [9s 16613]
[1z 16415] [2z 16708] [3z 16641] [4z 16760] [5z 16803] 
[6z 16757] [7z 16849]
------
针对某一个向听数或者牌出现概率，都可以看做是一个二项分布；而在统计次数43000+次的情况下除了配牌即听牌和一般手8向听的情况数据量稍显不足外，其余均基本可以用正态分布拟合。

向听数参考 [麻雀の数学](http://www10.plala.or.jp/rascalhp/mjmath.htm#12) 中的数据，忽略两个极端数据，基本所有数据都和理论值误差很小。通常手七向听相对误差在20%，但也在95%置信区间内。

对于各个牌在起手的出现分布，可以看到基本是差不多的。理论上无赤牌起手出现平均枚数为1/34 * 13=0.3824，其95%置信区间为(0.3778, 0.3869)，可以看到仅有1z也就是东的出现概率不在范围内（赤宝牌和其本体加起来算）。而因为是95%置信区间，出现一个偏差也是最可能出现的情况。

同时，我也尝试仅统计友人/铜/银/金/玉/2019年后的场次等，数据规模均在5000-20000不等，结果分布上没有明显区别，就不展示了。

综上，可以认为雀魂的牌山在发牌时是不存在暗改的情况的。你提到的简并性我不是很确定意思，以我查到的来看是说多个牌山对应同一个MD5的意思么？如果是这个意思的话那基本不用担心，虽然MD5早就被碰撞了，但是只是碰撞算法，对于这种特定长度和内容的信息想要完成MD5碰撞应该还是不可能的（密码学不是特别了解，这是我几年前学的时候的情况，如果现在有新结果了请指正）。而且即便是有碰撞算法复杂度也是很高的，对于每天要生成数不清的牌山的服务器来说成本回报实在相差太大。。

至于为什么没有听说天凤有这种牌谱呢？实际上如果完全没有这种牌谱才是没有好好的随机。没有的原因我觉得只是天凤官方并没有像雀魂做神仙牌谱的收集，之后民间自发的一些集锦；如果我在天凤中神仙了一波，更大可能是向好友和群里面炫耀一下，最多往博客之类的地方一挂就没了，宣传范围差了不知道多少数量级。而且天凤也是有不少神仙牌谱的，我虽然自己看的不多，之前翻天凤相关的比较大的日本网站还是有不少的。

而之后两个选项：
立直后一发自摸，这个和听牌牌型关系较大，同时雀魂铁头多所以一发会多；同时一发自摸相应少一些，不是很好用来比较，而且实现相比较麻烦些。以后有空可能会弄，但是我觉得意义不大，毕竟一发数据官方都给你统计好了。
里宝率：这个杠精多了肯定就高了，毕竟开得多。如果只是看第一张里宝的话可以用来统计，但是同样实现上不是很方便。而且如果开局牌山已经固定，在不串通的情况下想让大家留住里宝牌并立直；或是让人开杠都过于高难度了。包括故意让人一发、疯狂进张等，从技术上来说固定牌山下想做到实在有些难。

最后是你说的起手三九国士，比较懒就没数学上来算，我模拟了一下起手13张牌其中三张不完全相同的9牌然后摸牌15张强做国士自摸的概率应该是1/100000至1/200000这个数量级的。这还不如天和出现的概率低_(:3」∠)_只是因为有脑子的人都不会在这个时候做国士所以觉得神仙。雀魂现在每天局数（就是需要随机生成牌山的次数）我估摸着是百万级吧，9102年都过去五个月了出了这种牌谱我觉得很正常。

**Comment by Neerdge** [comment]
感谢您的调查！
雀魂官方说他们会考虑公开算法等信息。我个人秉持的观点也和官方一样，不存在中途改换的可能。既然起手等数据是正常的，那么就有理由相信雀魂官方确实是随机分配的牌山。

**Comment by lynkas** [comment]
虽然已经五年过去了，想到了一点，我们有没有统计过不同平台的起手向听数的平均差？
