### ISSUE TITLE
關於繁中設定會顯示亂碼的問題

### ISSUE THREAD

**Issue by QuntinMKII** [zyr17/MajsoulPaipuAnalyzer#7]
您好，在您提供的繁中設定檔(zh-TW.json)中第一行的"CHCP": "chcp 936"會導致程式使用時顯示亂碼
後發現將其值改成950後便可正常運作

**Comment by zyr17** [comment]
抱歉这个是我疏忽了，的确繁中应该是chcp 950的，操作失误不小心用简中的编码覆盖了，之后会修复。

**Comment by zyr17** [comment]
fixed
