### ISSUE TITLE
能解释下安定段位吗？

### ISSUE THREAD

**Issue by Sora233** [zyr17/MajsoulPaipuAnalyzer#8]
eg.
安定段位结果（置信水平0.95）：东风局银之间，南风局金之间
东风局安定段位：        2.0000
南风局安定段位：        4.1542

根据描述里的“安定段位即安定星数。”，这个数据东风安定段位是雀士2星，南风安定段位是雀杰4.15星？

4.15星是什么意思？

**Comment by zyr17** [comment]
如果你永远是雀杰并且永远在金南打和目前一样的战绩，那么最终你的星数是4.15星，即在4星和5星之间波动

实际上雀魂只有3星，因此表示你可以升段。只要安定段位大于3从期望上来讲都能到下一段
