### ISSUE TITLE
macos无法运行

### ISSUE THREAD

**Issue by jerryzmtz** [zyr17/MajsoulPaipuAnalyzer#9]
可以正确获取、转换牌谱，但是无法使用PaipuAnalyzer进行分析。
macOS Mojave 10.14.5 MacBook Pro(15-inch,2016)

Last login: Mon Jul  8 18:09:04 on ttys001
xxxMacBook-Pro:~ xxx$ /Users/xxx/Downloads/MajsoulPaipuAnalyzer-macos-x64/PaipuAnalyzer ; exit;
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

![WechatIMG66](https://user-images.githubusercontent.com/26083118/60803151-2396a480-a1ad-11e9-956f-a428faa260a5.png)

**Comment by zyr17** [comment]
感觉是程序出BUG了或者牌谱转换出了问题。。能否提供一下data/majsoul/你的ID/paipus.txt？我看下是什么问题

**Comment by jerryzmtz** [comment]
好的，麻煩了
[paipus.txt](https://github.com/zyr17/MajsoulPaipuAnalyzer/files/3373827/paipus.txt)

**Comment by zyr17** [comment]
有点奇怪。。我这边Windows和macOS都没复现BUG。。
我自己没有macOS设备，用的虚拟机，系统版本是10.14。请问你的系统是什么版本的，是什么语言环境？
另外，你是否修改过config.json？如果修改过的话麻烦也提供一下，也可以试试用原版config.json覆盖能否正常运行。
附件压缩包
[PaipuAn-debug.zip](https://github.com/zyr17/MajsoulPaipuAnalyzer/files/3377095/PaipuAn-debug.zip)
中是一个debug版本，使用方法是将其置于PaipuAnalyzer同一目录然后运行，注意不要更改文件名称。运行后不会直接将内容显示在命令行窗口中，而是会在目录生成debug.log，包括最终结果和大量额外的调试信息，我测试的时候大约需要10秒左右的运行时间。如果前面的尝试没有解决问题的话可以试一下这个debug版本，我看看debug.log来找找是什么问题。

**Comment by jerryzmtz** [comment]
不知为何，隔了几天重新走了一边流程又能运行了，谢谢！
